server {
    listen 80;
    listen [::]:80;
    server_name hm.if.io.kr;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name hm.if.io.kr;

    ssl_certificate /etc/letsencrypt/live/hm.if.io.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hm.if.io.kr/privkey.pem;

    root /var/www/haemi-web;
    index index.html;

    location = /index.html {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
