server {
    listen 80;
    listen [::]:80;
    server_name hm.if.io.kr;

    root /var/www/haemi-web;
    index index.html;

    location = /index.html {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
