-- AlterTable
ALTER TABLE "Vote" ADD COLUMN "startsAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Vote" ADD COLUMN "endsAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE "Vote" SET "endsAt" = "createdAt" + INTERVAL '7 days';
